version: '3'
services:
  # nextjs:
  #   build: ./04-chat-app
  #   ports:
  #     - "80:3000"  # Expose Next.js app on port 80
  #   environment:
  #     - API_SEARCH_SERVER=http://python-api:8055
  #   depends_on:
  #     - python-api

  python-api:
    build: ./03-search-api
    ports:
      - "8055:8055"  # Expose Python API locally, not accessible outside
    environment:
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY}  # Set Qdrant password
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}  # Set Qdrant password

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_storage:/redis/storage

volumes:
  qdrant_storage:
    driver: local
  redis_storage:
    driver: local